CREATE TABLE customer (
    customer_id            INT PRIMARY KEY,
    age                    INT,
    gender                 VARCHAR(20),
    item_purchased         VARCHAR(100),
    category               VARCHAR(100),
    purchase_amount_usd    NUMERIC(10,2),
    location               VARCHAR(100),
    size                   VARCHAR(20),
    color                  VARCHAR(50),
    season                 VARCHAR(50),
    review_rating          NUMERIC(3,1),
    subscription_status    VARCHAR(20),
    shipping_type          VARCHAR(50),
    discount_applied       VARCHAR(10),
    promo_code_used        VARCHAR(10),
    previous_purchases     INT,
    payment_method         VARCHAR(50),
    frequency_of_purchases INT
);
select*from customer limit10 ;
-- total revenue generated by gender
select gender,sum(purchase_amount) as revenue
from customer
group by gender

-- customer with more than average purchase amount after discount applied
select customer_id, purchase_amount
from customer
where discount_applied='Yes' and purchase_amount>=(select avg(purchase_amount) from customer)

-- top 5 products with highest average review rating
select item_purchased, round(avg(review_rating::numeric),2)as average_rating
from customer
group by item_purchased
order by average_rating desc
limit 5 ;
-- comparing the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

-- comparing average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id),
round(avg(purchase_amount),2) as avg_spend,
round(sum(purchase_amount),2) as total_revenue
from customer
group by subscription_status
order by avg_spend, total_revenue

-- 5 products with highest percentage of purchases with discount applied
select item_purchased,
round(100*sum(case when discount_applied='Yes' then 1 else 0 end)/count(*),2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5

-- segmenting customers into new ,returning and loyal basedd on their previous number of purchases and the count of each segment
with customer_type as (
select customer_id,previous_purchases,
case
	when previous_purchases=1 then 'new'
	when previous_purchases between 2 and 10 then 'returning'
	else 'loyal'
	end as customer_segment
	from customer
)
select customer_segment,count(*)as total_customers
from customer_type
group by customer_segment


-- top 3 most purchased product within each category
with item_counts as(
select category,
item_purchased,
count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as item_rank
from customer
group by category, item_purchased
)
select item_rank, category, item_purchased,total_orders
from item_counts
where item_rank<=3;

-- are customers who are repeat buyers are also likely to subscribe?
select subscription_status,
count(customer_id) as repeat_buyers
from customer
where previous_purchases>5
group by subscription_status

-- what is yhe revenue contribution of the each age group
select age_group,
sum(purchase_amount) as total_revenue
from customer
group by age_group
order by total_revenue desc

